# Organization details
org:
  name: "Shannon Labs"
  founder: "Hunter Bown"
  email: "hunter@shannonlabs.dev"
  site: "https://shannonlabs.dev"
  hf: "https://huggingface.co/hunterbown/shannon-control-unit"
  calendly: "https://calendly.com/hunter-shannonlabs/30min"

# Results to highlight
results:
  baseline_ppl: 15.14
  scu_ppl: 12.78
  improvement_pct: 15.6
  baseline_bpt: 3.920
  scu_bpt: 3.676

# Pilot specifications
pilot:
  compute_needed: "16-32 H100s"
  duration: "72-96 hours"
  success_threshold: "10%"
  overhead_target: "2%"

# Contacts
contacts:
  - name: "Technical Lead"
    company: "OpenAI"
    email: "tbd@openai.com"
    type: "hyperscaler"
  - name: "Research Partner"
    company: "Anthropic"
    email: "partnerships@anthropic.com"
    type: "anthropic"
  - name: "BD Team"
    company: "CoreWeave"
    email: "bd@coreweave.com"
    type: "gpu_provider"

# HN trigger conditions
hn_trigger:
  compute_secured: false
  time_to_target_improvement: null  # Set to percentage when 7B complete
  overhead_measured: null  # Set to percentage when measured
  profiler_traces: false