name: Generate fixed-Î» ablation CSV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu
          pip install transformers==4.39.3 peft==0.10.0
      - name: Generate fixed_5.0.csv
        env:
          TRANSFORMERS_NO_TF: '1'
        run: |
          python scripts/make_fixed_ablation.py --lambda_val 5.0 --steps 60 --out ablations/fixed_5.0.csv
          ls -lh ablations/
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ablations/fixed_5.0.csv
          if git diff --cached --quiet; then echo "No changes"; else git commit -m "ci: generate fixed_5.0.csv ablation (CI)"; git push; fi
      - name: Upload to Hugging Face (optional)
        if: env.HF_TOKEN != ''
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          python - << 'PY'
from huggingface_hub import HfApi
import os
api=HfApi(token=os.environ.get('HF_TOKEN'))
repo='hunterbown/shannon-control-unit'
api.upload_file(path_or_fileobj='ablations/fixed_5.0.csv', repo_id=repo, path_in_repo='fixed_5.0.csv', repo_type='model', commit_message='Add fixed_5.0.csv (CI)')
print('Uploaded fixed_5.0.csv to HF root')
PY

